scavengeobj = [
	{
		name: 'Lime',
		symbol: 'O',
		backgroundColor: '#4DFE89',
		weight: 20,
		type: 'resource',
		description: '',
		onCollection: 'gameData.limes += 1',
	},
	{
		name: 'Limes',
		symbol: 'OO',
		backgroundColor: '#4DFE89',
		weight: 10,
		type: 'resource',
		description: '',
		onCollection: 'gameData.limes += 2',
	},
	{
		name: 'Nutrition',
		symbol: 'R',
		backgroundColor: '#884DFF',
		weight: 5,
		type: 'ring',
		powerLevelRange: 20,
		description: 'Increases auto collect length by ',
		description2: ' seconds',
		onCollection: '',
	},
	{
		name: 'Nutrition Rate',
		symbol: 'R',
		backgroundColor: '#884DFF',
		weight: 5,
		type: 'ring',
		powerLevelRange: 2,
		description: 'Increases auto collect rate by ',
		description2: ' per second',
		onCollection: '',
	},
	{
		name: 'Smart Seller',
		symbol: 'R',
		backgroundColor: '#884DFF',
		weight: 5,
		type: 'ring',
		description: 'Stops delivering juice once coins have reached the maximum',
		onCollection: '',
	},
]